version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/etc/nginx/templates
      - ./volumes/nginx_logs:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
      - REMOTE_HOST_PORT=$REMOTE_HOST_PORT
      - HOST_PORT=$HOST_PORT
    network_mode: host
